#!/usr/bin/env python3
"""Rasterize the glyphs slate-spinner draws on the Slate 7 side screen.

Produces a C header with 8-bit alpha bitmaps (one entry per glyph, baseline
relative metrics) for two faces: the phrase text and the spinner "star"
frames (· ✢ * ✶ ✻ ✽; the text face also has the ▌ reveal head). Fonts: DejaVu Sans (Bitstream Vera licence, ships
with Ubuntu as fonts-dejavu-core). Run from the top of the tree:

    python3 scripts/gl-be3600/gen-spinner-font.py \
        package/utils/slate-spinner/src/font_data.h

Pillow is required (pip3 install pillow).
"""
import sys

from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
ASCII = [chr(c) for c in range(32, 127)]

# name, font file, pixel size, glyph list
FACES = [
    ("main", FONT, 17, ASCII + ["…", "▌"]),
    ("star", FONT, 28, list("·✢*✶✻✽")),
]


def raster(font, ch):
    """Return (adv16, bx, by, w, h, bytes) for one glyph, baseline relative."""
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    w, h = max(x1 - x0, 0), max(y1 - y0, 0)
    adv16 = int(round(font.getlength(ch) * 16))
    if w == 0 or h == 0:
        return adv16, 0, 0, 0, 0, b""
    pad = 2
    img = Image.new("L", (w + 2 * pad, h + 2 * pad), 0)
    ImageDraw.Draw(img).text((pad - x0, pad - y0), ch, font=font, fill=255,
                             anchor="ls")
    img = img.crop((pad, pad, pad + w, pad + h))
    return adv16, x0, y0, w, h, img.tobytes()


def main(out_path):
    lines = [
        "/* Generated by scripts/gl-be3600/gen-spinner-font.py - do not edit.",
        " * Glyph bitmaps rasterized from DejaVu Sans (Bitstream Vera licence).",
        " */",
        "#ifndef SLATE_SPINNER_FONT_DATA_H",
        "#define SLATE_SPINNER_FONT_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        "struct sg_glyph {",
        "\tuint16_t cp;      /* code point */",
        "\tint16_t adv16;    /* advance width, 1/16 px */",
        "\tint8_t bx, by;    /* bitmap origin relative to the pen (baseline) */",
        "\tuint8_t w, h;     /* bitmap size */",
        "\tuint32_t off;     /* offset into the face's pixel array */",
        "};",
        "",
        "struct sg_face {",
        "\tint ascent, descent;",
        "\tconst struct sg_glyph *glyphs;",
        "\tint nglyphs;",
        "\tconst uint8_t *pixels;",
        "};",
        "",
    ]
    for name, path, size, chars in FACES:
        font = ImageFont.truetype(path, size)
        ascent, descent = font.getmetrics()
        pixels = bytearray()
        glyphs = []
        for ch in chars:
            adv16, bx, by, w, h, data = raster(font, ch)
            glyphs.append((ord(ch), adv16, bx, by, w, h, len(pixels)))
            pixels += data
        lines.append(f"static const uint8_t sg_{name}_pixels[] = {{")
        for i in range(0, len(pixels), 24):
            chunk = ",".join(str(b) for b in pixels[i:i + 24])
            lines.append(f"\t{chunk},")
        if not pixels:
            lines.append("\t0,")
        lines.append("};")
        lines.append("")
        lines.append(f"static const struct sg_glyph sg_{name}_glyphs[] = {{")
        for cp, adv16, bx, by, w, h, off in glyphs:
            lines.append(f"\t{{ {cp}, {adv16}, {bx}, {by}, {w}, {h}, {off} }},")
        lines.append("};")
        lines.append("")
        lines.append(
            f"static const struct sg_face sg_{name} = {{ {ascent}, {descent}, "
            f"sg_{name}_glyphs, {len(glyphs)}, sg_{name}_pixels }};")
        lines.append("")
        print(f"{name}: {len(glyphs)} glyphs, {len(pixels)} bytes, "
              f"ascent {ascent} descent {descent}", file=sys.stderr)
    lines.append("#endif")
    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: gen-spinner-font.py <out.h>")
    main(sys.argv[1])
